apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: dc-metro-map-qxfa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: dc-metro-map-qxfa
    app.kubernetes.io/part-of: appstudio
  name: dc-metro-map-qxfa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: dc-metro-map-qxfa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: dc-metro-map-qxfa
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/release-service-happ-tenant/appstudio/dc-metro-map-qxfa@sha256:0340ed3dccff76d8cabd8e5256b913bcef24d8c7d05bddf4fb2c9ecac01b1dca
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
